# -*- mode: ruby -*-
# vi: set ft=ruby :
BOX_IMAGE = "debian/jessie64"

Vagrant.configure("2") do |config|
  config.vm.define "node1" do |node1|
    node1.vm.box = BOX_IMAGE
    node1.vm.hostname = "node1"
    node1.vm.network :private_network, ip: "10.0.0.11"
  end

  config.vm.define "node2" do |node2|
    node2.vm.box = BOX_IMAGE
    node2.vm.hostname = "node2"
    node2.vm.network :private_network, ip: "10.0.0.12"
  end

  config.vm.define "node3" do |node3|
    node3.vm.box = BOX_IMAGE
    node3.vm.hostname = "node3"
    node3.vm.network :private_network, ip: "10.0.0.13"
  end
  config.vm.provision "shell", inline: <<-SHELL
    apt-get install -y avahi-daemon libnss-mdns
  SHELL
end
